services:
  backend:
    image: django-docker
    container_name: backend-container
    restart: always

    build:
      context: ./django
      dockerfile: Dockerfile.backend

    volumes:
      - ./django:/home/ubuntu/webapp

    ports:
      - "1920:8000"

  frontend:
    image: react-vite-frontend
    container_name: frontend-container
    restart: always

    build:
      context: ./react
      dockerfile: Dockerfile.frontend

    volumes:
      - ./react/frontend:/home/ubuntu/webapp/frontend

    ports:
      - "2019:3000"
