FROM node:19

WORKDIR /home/ubuntu/webapp
RUN npm create vite frontend -- --template react

WORKDIR /home/ubuntu/webapp/frontend
COPY ./frontend/package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "dev", "--", "--port", "3000"]
EXPOSE 2019
