FROM python:3.8
ENV PYTHONUNBUFFERED 1

WORKDIR /home/ubuntu/webapp

COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

COPY . .
RUN python3 backend/manage.py migrate

CMD ["python3", "backend/manage.py", "runserver", "0.0.0.0:8000"]
EXPOSE 1920
